name = "lvr"
main = "src/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"

[triggers]
crons = ["0 2 1,11,21 * *"]

[[d1_databases]]
binding = "DB"
database_name = "lvr_db"
database_id = "3bafc9e4-a036-4099-beed-316598853cef"
